### ISSUE TITLE
non `utf-8` characters detected on album retrieval

### ISSUE THREAD

**Issue by cinghiopinghio** [coderkun/mcg#33] opened 2017-10-23 14:30 UTC
Managed to start `mcg` and found empty Library.
The error refers to some non `utf-8` chars detected on album retrieval.
Here you find the relevant part of the debug log:
```
2017-10-23 16:24:56,759 DEBUG: album: <mcg.client.MCGAlbum object at 0x7f76587c1a58>
2017-10-23 16:24:56,760 DEBUG: write: 'find album  ""\n'
2017-10-23 16:24:56,760 DEBUG: reading response
2017-10-23 16:24:56,809 ERROR: 'utf-8' codec can't decode byte 0xe2 in position 663: invalid continuation byte
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mcg/client.py", line 551, in _work
    method(*args)
  File "/usr/lib/python3.6/site-packages/mcg/client.py", line 406, in _load_albums
    for song in self._parse_list(self._call('find album ', album.get_title()), ['file']):
  File "/usr/lib/python3.6/site-packages/mcg/client.py", line 564, in _call
    return self._read()
  File "/usr/lib/python3.6/site-packages/mcg/client.py", line 599, in _read
    line = self._sock_read.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 663: invalid continuation byte
```

**Comment by coderkun** [comment] 2017-10-28 09:26
@cinghiopinghio, it looks like you have an invalid UTF-8 characters in the “title” field of one of your files. But the _empty_ “find album” call looks suspicious, too. In order to find out what is wrong, I need more information. I see two options to get more info:
1. Add more useful debug logging/output (the first line “album: …” is not very useful and should print out the actual album name).
2. Start with an empty MPD database and add tracks/albums until you get the error.

To solve this it depends on what the actual problem is. If it is a data issue, we can add a try/except block to make sure the application does not fail with bad data. But it might also be the case that the “find album” call needs to be fixed somehow. Let’s see …

**Comment by coderkun** [comment] 2017-11-18 10:06
@cinghiopinghio, any efforts to debug this issue or can we close it?

**Comment by cinghiopinghio** [comment] 2017-11-20 13:19
@coderkun , I found some filenames with non-utf-8 chars. Renaming those files helped. I haven't checked ALL files of my library tho. I'll eventually check all of them but it's a time consuming activity....

**Comment by coderkun** [comment] 2017-11-20 13:27
@cinghiopinghio, so the mentioned error is gone after renaming (some) files with non-UTF-8 characters?
Do you mind telling me a few example characters? I would like to try to reproduce the issue locally to improve the error handling.

**Comment by cinghiopinghio** [comment] 2017-11-21 10:24
In particular I used a new music folder with a subset of my database and noticed that the `non utf-8` error were solved by renaming some files. I didn't check the whole music database.
The offending filename is sth like: `05-�_etc_etc.mp3` (I don't know if that symbol include the bad encoded char). Even my file browser (Thunar) tell me that's an invalid encoding.

In any case `mcg` doesn't find the covers (I have a grid of placeholder icons), where should they go to be detected?

**Comment by coderkun** [comment] 2017-11-21 12:12
@cinghiopinghio, okay, thanks. Eventually I will try to catch such errors to make the application more robust ⇒ closing the issue though.

During connection (on the Connection panel) you have to specify the image directory either as local path (e. g. /home/cinghiopinghio/music) or as URL (e. g. http://localhost/music.

**Closed by coderkun** 2017-11-21 12:12 UTC
Labels: bug

**Comment by cinghiopinghio** [comment] 2017-11-23 14:06
@coderkun I don't understand how the image directory should be structured, how should I add covers? naive question: I added covers images to the music file tags, should mcg try to use those?

**Comment by coderkun** [comment] 2017-11-23 14:51
_mcg_ does not read the image from the tags since it is not reading the audio files itself, this would be up to MPD (see #30).

Instead it searches inside the folder of the file for an image which is either called the same name as the album, “cover” or “folder” plus png or jpg extension. When using a local folder it will fallbock to the first image file it finds regardless the name. The filename/folder that MPD provides is usually relative to the configured music directory, you should provide the same folder to _mcg_. You could also serve the music directory via http (with any web server) and provide the URL to _mcg_. _mcg_ then tries to load the image via the http URL.

An example:
MPD music library: /home/user/music
mcg image folder: /home/user/music
Song: /home/user/music/artist/nice album/01. music.flac
Cover files can be
* /home/user/music/artist/album/nice album.png
* /home/user/music/artist/album/cover.jpg
* /home/user/music/artist/album/folder.png
* /home/user/music/artist/album/localfile.jpg

Does any of these combinations work for you? I guess it would make sense to document this in the wiki but I hope you get the idea.

**Comment by cinghiopinghio** [comment] 2017-11-23 15:35
well I'll add:
- /home/user/music/artist/nice album/cover.{jpg,png}
Yes, it does work now. Thanks.

I think you should clarify this in the readme (if you have time).
